"""Advanced tools for sparse polynomials in $\K[x]$ or $\K[X]$. """

def smp_clear_denoms(f, u, ord, K, convert=False)
def smp_lift(f, u, ord, K)
def smp_eval_in(f, a, j, u, ord, K)
def smp_half_gcdex(f, g, ord, K)
def smp_gcdex(f, g, u, ord, K)
def smp_invert(f, g, u, ord, K)
def smp_resultant(f, g, u, ord, K)
def smp_discriminant(f, u, ord, K)
def smp_cofactors(f, g, u, ord, K)
def smp_gcd(f, g, u, ord, K)
def smp_lcm(f, g, u, ord, K)
def smp_ground_trunc(f, p, u, ord, K)
def smp_ground_monic(f, u, ord, K))
def smp_ground_content(f, u, ord, K)
def smp_ground_primitive(f, u, ord, K)
def smp_compose(f, g, u, ord, K)
def smp_decompose(f, u, ord, K)
def smp_sturm(f, u, ord, K)
def smp_sqf_norm(f, u, ord, K)
def smp_sqf_part(f, u, ord, K)
def smp_sqf_list(f, u, ord, K, all=False)
def smp_sqf_list_include(f, u, ord, K, all=False)
def smp_factor_list(f, u, ord, K)
def smp_factor_list_include(f, u, ord, K)
def smp_real_intervals(f, u, ord, K, eps, inf, sup, fast)
def smp_complex_intervals(f, u, ord, K, eps, inf, sup, fast)
def smp_refine_real_root(f, s, t, u, ord, K, eps, steps, fast)
def smp_refine_complex_root(f, s, t, u, ord, K, eps, steps, fast)
def smp_count_real_roots(f, u, ord, K, inf, sup)
def smp_count_complex_roots(f, u, ord, K, inf, sup)

def smp_zero_p(f, u)
def smp_one_p(f, u, K)
def smp_ground_p(f, u)
def smp_sqf_p(f, u, ord, K)
def smp_monic_p(f, u, ord, K)
def smp_primitive_p(f, u, ord, K)
def smp_linear_p(f, u, ord, K)
def smp_homogeneous_p(f, u, ord, K)

